CREATE DATABASE siteMercadoDB;

CREATE TABLE ProdutosTB(
	IdProduto INT PRIMARY KEY IDENTITY,
	Nome VARCHAR(80) NOT NULL,
	Valor DECIMAL(6,2) CHECK (Valor > 0),
	Unidade VARCHAR(50) NOT NULL,
	Quantidade SMALLINT,
	Imagem VARCHAR(100) NOT NULL
) 

SELECT * FROM ProdutosTB;

CREATE TABLE UsuáriosTB(
	IdUsuário INT PRIMARY KEY IDENTITY,
	Email VARCHAR(120) NOT NULL UNIQUE,
	Nome VARCHAR(120) NOT NULL,
	Senha VARCHAR(150) NOT NULL,
	Salt VARCHAR(16) NOT NULL,
	Cargo VARCHAR(30) NOT NULL
)

SELECT * FROM ProdutosTB;

CREATE TABLE EndereçosTB(
    IdEndereço INT PRIMARY KEY,
    IdUsuário INT FOREIGN KEY REFERENCES UsuáriosTB(IdUsuário),
	Número SMALLINT,
    CEP NVARCHAR(10),
    Rua NVARCHAR(255),
    Cidade NVARCHAR(100),
    Estado NVARCHAR(50),
);

SELECT * FROM EndereçosTB;
