CREATE DATABASE siteMercadoDB;

CREATE TABLE [ProdutosTB](
	IdProduto INT PRIMARY KEY IDENTITY,
	Nome VARCHAR(80) NOT NULL,
	[Valor R$] DECIMAL(6,2) CHECK ([Valor R$] > 0),
	Unidade VARCHAR(50) NOT NULL,
	Quantidade SMALLINT,
	Imagem VARCHAR(100) NOT NULL
) 

SELECT * FROM ProdutosTB;

CREATE TABLE [UsuáriosTB](
	IdUsuário INT PRIMARY KEY IDENTITY,
	Email VARCHAR(120) NOT NULL UNIQUE,
	Nome VARCHAR(120) NOT NULL,
	Endereço VARCHAR(500),
	Cargo VARCHAR(70) NOT NULL
)

SELECT * FROM UsuáriosTB;